### ISSUE TITLE
Gestione eccezioni

### ISSUE THREAD

**Issue by davide-targa** [dbraga/git-wizzy#11]
Per sbaglio ho chiamato il file di configurazione `wizzy-config.yml` invece di `wizzy_config.yml`.
Risultato:

```
File wizzy_config.yml not found!
Traceback (most recent call last):
  File "./wizzy", line 223, in <module>
    exec_arg(sys.argv)
  File "./wizzy", line 213, in exec_arg
    globals()[argv[1]]()
  File "./wizzy", line 130, in install
    os.makedirs(configurationFile()['wizzy_cache_directory'])
TypeError: 'NoneType' object is not subscriptable
```

Forse è il caso di gestire l'eccezione

**Comment by dbraga** [comment]
Giusto
