### ISSUE TITLE
wizzy doctor

### ISSUE THREAD

**Issue by davide-targa** [dbraga/git-wizzy#13]
Ho modificato (apposta) il file di configurazione come segue:

```
files: [lib/ruby_provisioning_api/config/google_foobar.yml]
wizzy_cache_directory: .wizzy
wizzy_directory: .
wizzy_remote: false
```

nota il google_foobar.yml in files (che ovviamente non esiste).
Poi:

```
$ wizzy doctor
Wizzy: Checking files inside wizzy_config.yml ...
Traceback (most recent call last):
  File "./wizzy", line 223, in <module>
    exec_arg(sys.argv)
  File "./wizzy", line 213, in exec_arg
    globals()[argv[1]]()
  File "./wizzy", line 71, in doctor
    remove(element)
  File "./wizzy", line 98, in remove
    configurationFile()['files'].update({'files': array})
AttributeError: 'list' object has no attribute 'update'
```

E' da gestire anche questo o sono io che non ho capito a cosa serve wizzy doctor?

**Comment by dbraga** [comment]
Interessante. non fa quello che deve fare. Ci guardo
